# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import popo_attribute_tracker.attribute_tracker


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('meeting_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('place', 'place'), ('person', 'person'), ('shortest', 'shortest')], max_length=8)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('progress', 'progress'), ('ended', 'ended'), ('canceled', 'canceled')], default='pending', max_length=8)),
            ],
            bases=(models.Model, popo_attribute_tracker.attribute_tracker.AttributeTrackerMixin),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.NullBooleanField(default=None)),
                ('arrived', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
            ],
            bases=(models.Model, popo_attribute_tracker.attribute_tracker.AttributeTrackerMixin),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='place',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='meeting.Place'),
        ),
    ]
